spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: root
    password: password
    initialize: true
    platform: mysql
    initialization-mode: always
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: none
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: root
    password: password
    initialize: true
    platform: mysql
    initialization-mode : always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto : none
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create

