version: '3.3'

services: 
  mysql:
    image: mysql:5.7.25
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  # nginx:
  #  container_name: some-nginx
  #  image: nginx:1.13
  #  restart: always
  #  ports:
  #  - 80:80
  #  - 443:443
  #  volumes:
  #  - ./nginx/conf.d:/etc/nginx/conf.d
  #  depends_on:
  #  - server
  server:
    restart: always
    build: ./server
    working_dir: /server
    environment:
      - DATABASE_HOST=${MYSQL_HOST}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_PORT=${MYSQL_PORT}
    volumes:
      - ./server:/server
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
      - 8080:8080
      - 5005:5005
    command: ./mvnw clean spring-boot:run -Dspring.profiles.active=container -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 -Dspring.profiles.active=container"
    depends_on:
      - mysql
  client:
    depends_on:
      - server
    build:
      context: ./client
    command: yarn start
    working_dir: /usr/app
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"