spring:
  security:
    oauth2:
      resource:
        filter-order : 3
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: root
    password: password
    platform: mysql
    initialization-mode: never

    jpa:
      show-sql : true
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: update
---
spring:
  profiles: container
  security:
    oauth2:
      resource:
        filter-order: 3
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: root
    password: password
    platform: mysql
    initialization-mode : never
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql : true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create

